name: oscam
base: core20
adopt-info: oscam
summary: OSCam is an Open Source Conditional Access Module software
description: |
  OSCam is an Open Source Conditional Access Module software,
  based on the very good MpCS version 0.9d

  All configuration files can be found under
  /var/snap/oscam/current/etc/oscam/ The Web Interface listens on
  port 8083 by default.

  Please connect the raw-usb and process-control interfaces
  before setting up your soft CAM.

  To connect USB serial readers like a smartmouse/easymouse, follow
  the instructions at: https://snapcraft.io/docs/hotplug-support

grade: stable
confinement: strict

architectures:
  - build-on: armhf
  - build-on: arm64
  - build-on: amd64

apps:
   oscam:
     command: usr/bin/oscam -c /etc/oscam -r 2
     daemon: simple
     plugs:
       - network
       - network-bind
       - process-control
       - raw-usb
       - serial-port
   list-smargo:
     command: usr/bin/list_smargo
     plugs:
       - network
       - network-bind
       - process-control
       - raw-usb
       - serial-port

layout:
  /etc/oscam:
    bind: $SNAP_DATA/etc/oscam
  /var/log/oscam:
    bind: $SNAP_DATA/var/log/oscam
  
package-repositories:
 - type: apt
   ppa: gandalf-der-grosse/main

parts:
  oscam:
    source: .
    plugin: nil
    stage-packages:
      - libpcsclite1
      - libpng16-16
      - libssl1.1
      - libusb-1.0-0
      - oscam
      - oscam-listsmargo
      - usbutils
      - zlib1g
    override-build: |
      #snapcraftctl build
      VER="$(zcat $SNAPCRAFT_PART_INSTALL/usr/share/doc/oscam/changelog.Debian.gz | \
               grep -m1 "^oscam (" | sed 's/^.*(//;s/-[0-9]ppa.*$//')"
      snapcraftctl set-version "$VER"
